# Generated by Django 5.1.2 on 2024-10-16 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('discount_start', models.DateTimeField(blank=True, null=True)),
                ('discount_end', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='menuapi.category')),
            ],
        ),
        migrations.CreateModel(
            name='DailyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('main_course1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_course1_of_day', to='menuapi.menuitem')),
                ('main_course2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_course2_of_day', to='menuapi.menuitem')),
                ('soup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soup_of_day', to='menuapi.menuitem')),
            ],
        ),
    ]
