# Generated by Django 5.1.2 on 2024-11-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapi', '0003_menuitem_image_alter_menuitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='menu_items', to='menuapi.ingredient'),
        ),
    ]
