# Generated by Django 5.1.2 on 2024-11-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapi', '0006_alter_category_options_category_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
