# Generated by Django 5.1.2 on 2024-12-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapi', '0007_alter_menuitem_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=0, max_digits=6)),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_pizza',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='available_sizes',
            field=models.ManyToManyField(blank=True, related_name='pizzas', to='menuapi.pizzasize'),
        ),
    ]
