# Generated by Django 5.1.2 on 2024-12-05 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapi', '0008_pizzasize_menuitem_is_pizza_menuitem_available_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='available_sizes',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='is_pizza',
        ),
        migrations.CreateModel(
            name='PizzaPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_32', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='32 cm ár')),
                ('price_40', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='40 cm ár')),
                ('price_60', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='60 cm ár')),
                ('menu_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pizza_pricing', to='menuapi.menuitem')),
            ],
        ),
        migrations.DeleteModel(
            name='PizzaSize',
        ),
    ]
