# Generated by Django 5.1.2 on 2024-12-05 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapi', '0009_remove_menuitem_available_sizes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='discount_end',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='discount_start',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='menuapi.category', verbose_name='Kategória'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Leírás'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_items/', verbose_name='Kép'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='menu_items', to='menuapi.ingredient', verbose_name='Összetevők'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Elrejtve'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Név'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=0, help_text='Nem pizza esetén az ár', max_digits=6, verbose_name='Ár'),
        ),
        migrations.AlterField(
            model_name='pizzapricing',
            name='price_32',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True, verbose_name='32 cm ár'),
        ),
        migrations.AlterField(
            model_name='pizzapricing',
            name='price_40',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True, verbose_name='40 cm ár'),
        ),
        migrations.AlterField(
            model_name='pizzapricing',
            name='price_60',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True, verbose_name='60 cm ár'),
        ),
    ]
