# Generated by Django 5.1.2 on 2024-12-06 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuapi', '0012_menuitem_discount_end_menuitem_discount_price_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='menuitem',
            table=None,
        ),
    ]
